//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public long ID_Carrito { get; set; }
        public long ID_Usuario { get; set; }
        public long ID_Producto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaCarrito { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
