//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public long ID_Carrito { get; set; }
        public long ID_Usuario { get; set; }
        public long ID_Producto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaCarrito { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
