//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int id_compras { get; set; }
        public long Empresa { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
    }
}
