//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Detalle
    {
        public long ID_Detalle { get; set; }
        public long ID_Factura { get; set; }
        public long ID_Producto { get; set; }
        public decimal PrecioPagado { get; set; }
        public int CantidadPagado { get; set; }
        public decimal ImpuestoPagado { get; set; }
    
        public virtual Factura_Encabezado Factura_Encabezado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
