//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public long ID_Pedido { get; set; }
        public long ID_Cliente { get; set; }
        public string ID_Transaccion { get; set; }
        public long ID_Factura { get; set; }
        public int Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
