//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public long ID_Pedido { get; set; }
        public long ID_Cliente { get; set; }
        public string ID_Transaccion { get; set; }
        public long ID_Factura { get; set; }
        public int Estado { get; set; }
    
        public virtual Factura_Encabezado Factura_Encabezado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
