//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyectoSC_601
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public long ID_Proveedor { get; set; }
        public int ID_Identificacion { get; set; }
        public string Nombre_Proveedor { get; set; }
        public string Apellido_Proveedor { get; set; }
        public string Cedula_Proveedor { get; set; }
        public string Direccion_Exacta { get; set; }
        public int Estado_Proveedor { get; set; }
        public long Empresa { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Identificacion Identificacion { get; set; }
    }
}
